DROP TABLE IF EXISTS access_count;

CREATE TABLE access_count (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    room_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    granted BOOLEAN NOT NULL
);
